// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package tests

import (
	"testing"

	"github.com/planetary-social/scuttlego/fixtures"
	"github.com/planetary-social/scuttlego/service/domain/replication"
	"github.com/planetary-social/scuttlego/service/domain/replication/ebt"
	"github.com/planetary-social/scuttlego/service/domain/replication/gossip"
)

// Injectors from wire.go:

func BuildTestReplication(t *testing.T) (TestReplication, error) {
	logger := fixtures.TestLogger(t)
	sessionTracker := ebt.NewSessionTracker()
	rawMessageHandlerMock := NewRawMessageHandlerMock()
	contactsRepositoryMock := NewContactsRepositoryMock()
	contactsCache := replication.NewContactsCache(contactsRepositoryMock)
	messageStreamerMock := NewMessageStreamerMock()
	sessionRunner := ebt.NewSessionRunner(logger, rawMessageHandlerMock, contactsCache, messageStreamerMock)
	replicator := ebt.NewReplicator(sessionTracker, sessionRunner, logger)
	manager := gossip.NewManager(logger, contactsCache)
	gossipReplicator, err := gossip.NewGossipReplicator(manager, rawMessageHandlerMock, logger)
	if err != nil {
		return TestReplication{}, err
	}
	negotiator := replication.NewNegotiator(logger, replicator, gossipReplicator)
	testReplication := TestReplication{
		Negotiator:         negotiator,
		RawMessageHandler:  rawMessageHandlerMock,
		ContactsRepository: contactsRepositoryMock,
		MessageStreamer:    messageStreamerMock,
	}
	return testReplication, nil
}

// wire.go:

type TestReplication struct {
	Negotiator *replication.Negotiator

	RawMessageHandler  *RawMessageHandlerMock
	ContactsRepository *ContactsRepositoryMock
	MessageStreamer    *MessageStreamerMock
}
