// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/boreq/errors"
	"github.com/google/wire"
	"github.com/planetary-social/go-ssb/identity"
	"github.com/planetary-social/go-ssb/logging"
	"github.com/planetary-social/go-ssb/network"
	"github.com/planetary-social/go-ssb/network/boxstream"
	"github.com/planetary-social/go-ssb/network/rpc"
	"github.com/planetary-social/go-ssb/scuttlebutt"
	"github.com/planetary-social/go-ssb/scuttlebutt/adapters"
	"github.com/planetary-social/go-ssb/scuttlebutt/commands"
	"github.com/planetary-social/go-ssb/scuttlebutt/feeds"
	"github.com/planetary-social/go-ssb/scuttlebutt/feeds/content/transport"
	"github.com/planetary-social/go-ssb/scuttlebutt/feeds/formats"
	"github.com/planetary-social/go-ssb/scuttlebutt/replication"
	"github.com/sirupsen/logrus"
	"go.etcd.io/bbolt"
	"time"
)

// Injectors from wire.go:

func BuildAdapters(tx *bbolt.Tx, private identity.Private) (commands.Adapters, error) {
	messageContentMappings := transport.DefaultMappings()
	logger := newLogger()
	marshaler, err := transport.NewMarshaler(messageContentMappings, logger)
	if err != nil {
		return commands.Adapters{}, err
	}
	scuttlebutt := formats.NewScuttlebutt(marshaler)
	v := newFormats(scuttlebutt)
	rawMessageIdentifier := formats.NewRawMessageIdentifier(v)
	public := newPublicIdentity(private)
	socialGraphRepository := adapters.NewSocialGraphRepository(tx, public)
	boltFeedRepository := adapters.NewBoltFeedRepository(tx, rawMessageIdentifier, socialGraphRepository, scuttlebutt)
	commandsAdapters := commands.Adapters{
		Feed:        boltFeedRepository,
		SocialGraph: socialGraphRepository,
	}
	return commandsAdapters, nil
}

func BuildAdaptersForContactsRepository(tx *bbolt.Tx, private identity.Private) (adapters.Repositories, error) {
	messageContentMappings := transport.DefaultMappings()
	logger := newLogger()
	marshaler, err := transport.NewMarshaler(messageContentMappings, logger)
	if err != nil {
		return adapters.Repositories{}, err
	}
	scuttlebutt := formats.NewScuttlebutt(marshaler)
	v := newFormats(scuttlebutt)
	rawMessageIdentifier := formats.NewRawMessageIdentifier(v)
	public := newPublicIdentity(private)
	socialGraphRepository := adapters.NewSocialGraphRepository(tx, public)
	boltFeedRepository := adapters.NewBoltFeedRepository(tx, rawMessageIdentifier, socialGraphRepository, scuttlebutt)
	repositories := adapters.Repositories{
		Feed:  boltFeedRepository,
		Graph: socialGraphRepository,
	}
	return repositories, nil
}

func BuildService(private identity.Private) (Service, error) {
	networkKey := boxstream.NewDefaultNetworkKey()
	handshaker, err := boxstream.NewHandshaker(private, networkKey)
	if err != nil {
		return Service{}, err
	}
	logger := newLogger()
	mux := rpc.NewMux(logger)
	peerInitializer := network.NewPeerInitializer(handshaker, mux, logger)
	db, err := newBolt()
	if err != nil {
		return Service{}, err
	}
	repositoriesFactory := newContactRepositoriesFactory(private)
	boltContactsRepository := adapters.NewBoltContactsRepository(db, repositoriesFactory)
	manager := replication.NewManager(logger, boltContactsRepository)
	adaptersFactory := newAdaptersFactory(private)
	transactionProvider := adapters.NewTransactionProvider(db, adaptersFactory)
	messageContentMappings := transport.DefaultMappings()
	marshaler, err := transport.NewMarshaler(messageContentMappings, logger)
	if err != nil {
		return Service{}, err
	}
	formatsScuttlebutt := formats.NewScuttlebutt(marshaler)
	v := newFormats(formatsScuttlebutt)
	rawMessageIdentifier := formats.NewRawMessageIdentifier(v)
	rawMessageHandler := commands.NewRawMessageHandler(transactionProvider, rawMessageIdentifier, logger)
	gossipReplicator, err := replication.NewGossipReplicator(manager, rawMessageHandler, logger)
	if err != nil {
		return Service{}, err
	}
	peerManager := scuttlebutt.NewPeerManager(gossipReplicator, logger)
	listener, err := network.NewListener(peerInitializer, peerManager, logger)
	if err != nil {
		return Service{}, err
	}
	dialer, err := network.NewDialer(peerInitializer, logger)
	if err != nil {
		return Service{}, err
	}
	redeemInviteHandler := commands.NewRedeemInviteHandler(dialer, transactionProvider, networkKey, private, mux, logger)
	followHandler := commands.NewFollowHandler(transactionProvider, private, logger)
	connectHandler := commands.NewConnectHandler(dialer, peerManager, logger)
	application := commands.Application{
		RedeemInvite: redeemInviteHandler,
		Follow:       followHandler,
		Connect:      connectHandler,
	}
	service := NewService(listener, application)
	return service, nil
}

// wire.go:

var applicationSet = wire.NewSet(wire.Struct(new(commands.Application), "*"), commands.NewRedeemInviteHandler, commands.NewFollowHandler, commands.NewConnectHandler)

var replicatorSet = wire.NewSet(replication.NewManager, wire.Bind(new(replication.ReplicationManager), new(*replication.Manager)), replication.NewGossipReplicator, wire.Bind(new(scuttlebutt.Replicator), new(*replication.GossipReplicator)))

var formatsSet = wire.NewSet(
	newFormats, formats.NewScuttlebutt, transport.NewMarshaler, wire.Bind(new(formats.Marshaler), new(*transport.Marshaler)), transport.DefaultMappings, formats.NewRawMessageIdentifier, wire.Bind(new(commands.RawMessageIdentifier), new(*formats.RawMessageIdentifier)), wire.Bind(new(adapters.RawMessageIdentifier), new(*formats.RawMessageIdentifier)),
)

type TestAdapters struct {
	Feed *adapters.BoltFeedRepository
}

func newAdaptersFactory(local identity.Private) adapters.AdaptersFactory {
	return func(tx *bbolt.Tx) (commands.Adapters, error) {
		return BuildAdapters(tx, local)
	}
}

func newContactRepositoriesFactory(local identity.Private) adapters.RepositoriesFactory {
	return func(tx *bbolt.Tx) (adapters.Repositories, error) {
		return BuildAdaptersForContactsRepository(tx, local)
	}
}

func newBolt() (*bbolt.DB, error) {
	b, err := bbolt.Open("/tmp/tmp.bolt.db", 0600, &bbolt.Options{Timeout: 5 * time.Second})
	if err != nil {
		return nil, errors.Wrap(err, "could not open the database, is something else reading it?")
	}
	return b, nil
}

func newPublicIdentity(p identity.Private) identity.Public {
	return p.Public()
}

func newLogger() logging.Logger {
	log := logrus.New()
	log.SetLevel(logrus.DebugLevel)
	return logging.NewLogrusLogger(log, "main")
}

func newFormats(
	s *formats.Scuttlebutt,
) []feeds.FeedFormat {
	return []feeds.FeedFormat{
		s,
	}
}
