// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"path"
	"path/filepath"
	"testing"
	"time"

	"github.com/boreq/errors"
	badger2 "github.com/dgraph-io/badger/v3"
	"github.com/google/wire"
	"github.com/planetary-social/scuttlego/fixtures"
	"github.com/planetary-social/scuttlego/logging"
	migrations2 "github.com/planetary-social/scuttlego/migrations"
	"github.com/planetary-social/scuttlego/service/adapters"
	"github.com/planetary-social/scuttlego/service/adapters/badger"
	"github.com/planetary-social/scuttlego/service/adapters/badger/notx"
	"github.com/planetary-social/scuttlego/service/adapters/bolt"
	ebt2 "github.com/planetary-social/scuttlego/service/adapters/ebt"
	"github.com/planetary-social/scuttlego/service/adapters/invites"
	"github.com/planetary-social/scuttlego/service/adapters/migrations"
	"github.com/planetary-social/scuttlego/service/adapters/mocks"
	"github.com/planetary-social/scuttlego/service/adapters/pubsub"
	"github.com/planetary-social/scuttlego/service/app"
	"github.com/planetary-social/scuttlego/service/app/commands"
	"github.com/planetary-social/scuttlego/service/app/queries"
	"github.com/planetary-social/scuttlego/service/domain"
	replication2 "github.com/planetary-social/scuttlego/service/domain/blobs/replication"
	"github.com/planetary-social/scuttlego/service/domain/feeds/content/transport"
	"github.com/planetary-social/scuttlego/service/domain/feeds/formats"
	"github.com/planetary-social/scuttlego/service/domain/graph"
	"github.com/planetary-social/scuttlego/service/domain/identity"
	invites2 "github.com/planetary-social/scuttlego/service/domain/invites"
	mocks2 "github.com/planetary-social/scuttlego/service/domain/mocks"
	"github.com/planetary-social/scuttlego/service/domain/network"
	"github.com/planetary-social/scuttlego/service/domain/network/local"
	"github.com/planetary-social/scuttlego/service/domain/replication"
	"github.com/planetary-social/scuttlego/service/domain/replication/ebt"
	"github.com/planetary-social/scuttlego/service/domain/replication/gossip"
	"github.com/planetary-social/scuttlego/service/domain/rooms"
	"github.com/planetary-social/scuttlego/service/domain/rooms/tunnel"
	transport2 "github.com/planetary-social/scuttlego/service/domain/transport"
	"github.com/planetary-social/scuttlego/service/domain/transport/boxstream"
	"github.com/planetary-social/scuttlego/service/domain/transport/rpc"
	"github.com/planetary-social/scuttlego/service/domain/transport/rpc/mux"
	network2 "github.com/planetary-social/scuttlego/service/ports/network"
	pubsub2 "github.com/planetary-social/scuttlego/service/ports/pubsub"
	rpc2 "github.com/planetary-social/scuttlego/service/ports/rpc"
	"go.etcd.io/bbolt"
)

// Injectors from wire.go:

func BuildBadgerNoTxTestAdapters(t *testing.T) BadgerNoTxTestAdapters {
	db := fixtures.Badger(t)
	txAdaptersFactory := noTxTxAdaptersFactory()
	transactionProvider := notx.NewTransactionProvider(db, txAdaptersFactory)
	noTxBlobWantListRepository := notx.NewNoTxBlobWantListRepository(transactionProvider)
	testAdapters := notx.TestAdapters{
		NoTxBlobWantListRepository: noTxBlobWantListRepository,
	}
	banListHasherMock := mocks.NewBanListHasherMock()
	currentTimeProviderMock := mocks.NewCurrentTimeProviderMock()
	rawMessageIdentifierMock := mocks.NewRawMessageIdentifierMock()
	testAdaptersDependencies := badger.TestAdaptersDependencies{
		BanListHasher:        banListHasherMock,
		CurrentTimeProvider:  currentTimeProviderMock,
		RawMessageIdentifier: rawMessageIdentifierMock,
	}
	badgerTestAdaptersFactory := testAdaptersFactory()
	testTransactionProvider := badger.NewTestTransactionProvider(db, testAdaptersDependencies, badgerTestAdaptersFactory)
	badgerTestAdaptersDependencies := &badger.TestAdaptersDependencies{
		BanListHasher:        banListHasherMock,
		CurrentTimeProvider:  currentTimeProviderMock,
		RawMessageIdentifier: rawMessageIdentifierMock,
	}
	badgerNoTxTestAdapters := BadgerNoTxTestAdapters{
		NoTxTestAdapters:    testAdapters,
		TransactionProvider: testTransactionProvider,
		Dependencies:        badgerTestAdaptersDependencies,
	}
	return badgerNoTxTestAdapters
}

func BuildBadgerTestAdapters(t *testing.T) BadgerTestAdapters {
	db := fixtures.Badger(t)
	banListHasherMock := mocks.NewBanListHasherMock()
	currentTimeProviderMock := mocks.NewCurrentTimeProviderMock()
	rawMessageIdentifierMock := mocks.NewRawMessageIdentifierMock()
	testAdaptersDependencies := badger.TestAdaptersDependencies{
		BanListHasher:        banListHasherMock,
		CurrentTimeProvider:  currentTimeProviderMock,
		RawMessageIdentifier: rawMessageIdentifierMock,
	}
	badgerTestAdaptersFactory := testAdaptersFactory()
	testTransactionProvider := badger.NewTestTransactionProvider(db, testAdaptersDependencies, badgerTestAdaptersFactory)
	badgerTestAdaptersDependencies := &badger.TestAdaptersDependencies{
		BanListHasher:        banListHasherMock,
		CurrentTimeProvider:  currentTimeProviderMock,
		RawMessageIdentifier: rawMessageIdentifierMock,
	}
	badgerTestAdapters := BadgerTestAdapters{
		TransactionProvider: testTransactionProvider,
		Dependencies:        badgerTestAdaptersDependencies,
	}
	return badgerTestAdapters
}

func buildBadgerNoTxTxAdapters(tx *badger2.Txn) (notx.TxAdapters, error) {
	banListHasherMock := mocks.NewBanListHasherMock()
	banListRepository := badger.NewBanListRepository(tx, banListHasherMock)
	blobRepository := badger.NewBlobRepository(tx)
	currentTimeProviderMock := mocks.NewCurrentTimeProviderMock()
	blobWantListRepository := badger.NewBlobWantListRepository(tx, currentTimeProviderMock)
	feedWantListRepository := badger.NewFeedWantListRepository(tx, currentTimeProviderMock)
	rawMessageIdentifierMock := mocks.NewRawMessageIdentifierMock()
	messageRepository := badger.NewMessageRepository(tx, rawMessageIdentifierMock)
	receiveLogRepository := badger.NewReceiveLogRepository(tx, messageRepository)
	private, err := identity.NewPrivate()
	if err != nil {
		return notx.TxAdapters{}, err
	}
	public := privateIdentityToPublicIdentity(private)
	graphHops := _wireHopsValue
	socialGraphRepository := badger.NewSocialGraphRepository(tx, public, graphHops, banListRepository)
	pubRepository := badger.NewPubRepository(tx)
	txAdapters := notx.TxAdapters{
		BanListRepository:      banListRepository,
		BlobRepository:         blobRepository,
		BlobWantListRepository: blobWantListRepository,
		FeedWantListRepository: feedWantListRepository,
		MessageRepository:      messageRepository,
		ReceiveLogRepository:   receiveLogRepository,
		SocialGraphRepository:  socialGraphRepository,
		PubRepository:          pubRepository,
	}
	return txAdapters, nil
}

var (
	_wireHopsValue = hops
)

func buildBadgerTestAdapters(txn *badger2.Txn, testAdaptersDependencies badger.TestAdaptersDependencies) (badger.TestAdapters, error) {
	banListHasherMock := testAdaptersDependencies.BanListHasher
	banListRepository := badger.NewBanListRepository(txn, banListHasherMock)
	blobRepository := badger.NewBlobRepository(txn)
	currentTimeProviderMock := testAdaptersDependencies.CurrentTimeProvider
	blobWantListRepository := badger.NewBlobWantListRepository(txn, currentTimeProviderMock)
	feedWantListRepository := badger.NewFeedWantListRepository(txn, currentTimeProviderMock)
	rawMessageIdentifierMock := testAdaptersDependencies.RawMessageIdentifier
	messageRepository := badger.NewMessageRepository(txn, rawMessageIdentifierMock)
	receiveLogRepository := badger.NewReceiveLogRepository(txn, messageRepository)
	private, err := identity.NewPrivate()
	if err != nil {
		return badger.TestAdapters{}, err
	}
	public := privateIdentityToPublicIdentity(private)
	graphHops := _wireGraphHopsValue
	socialGraphRepository := badger.NewSocialGraphRepository(txn, public, graphHops, banListRepository)
	pubRepository := badger.NewPubRepository(txn)
	messageContentMappings := transport.DefaultMappings()
	logger := fixtures.SomeLogger()
	marshaler, err := transport.NewMarshaler(messageContentMappings, logger)
	if err != nil {
		return badger.TestAdapters{}, err
	}
	messageHMAC := formats.NewDefaultMessageHMAC()
	scuttlebutt := formats.NewScuttlebutt(marshaler, messageHMAC)
	feedRepository := badger.NewFeedRepository(txn, socialGraphRepository, receiveLogRepository, messageRepository, pubRepository, blobRepository, banListRepository, scuttlebutt)
	testAdapters := badger.TestAdapters{
		BanListRepository:      banListRepository,
		BlobRepository:         blobRepository,
		BlobWantListRepository: blobWantListRepository,
		FeedWantListRepository: feedWantListRepository,
		MessageRepository:      messageRepository,
		ReceiveLogRepository:   receiveLogRepository,
		SocialGraphRepository:  socialGraphRepository,
		PubRepository:          pubRepository,
		FeedRepository:         feedRepository,
	}
	return testAdapters, nil
}

var (
	_wireGraphHopsValue = hops
)

func BuildTxTestAdapters(tx *bbolt.Tx) (TxTestAdapters, error) {
	messageContentMappings := transport.DefaultMappings()
	logger := fixtures.SomeLogger()
	marshaler, err := transport.NewMarshaler(messageContentMappings, logger)
	if err != nil {
		return TxTestAdapters{}, err
	}
	messageHMAC := formats.NewDefaultMessageHMAC()
	scuttlebutt := formats.NewScuttlebutt(marshaler, messageHMAC)
	v := newFormats(scuttlebutt)
	rawMessageIdentifier := formats.NewRawMessageIdentifier(v)
	messageRepository := bolt.NewMessageRepository(tx, rawMessageIdentifier)
	private, err := identity.NewPrivate()
	if err != nil {
		return TxTestAdapters{}, err
	}
	public := privateIdentityToPublicIdentity(private)
	graphHops := _wireHopsValue2
	banListHasherMock := mocks.NewBanListHasherMock()
	banListRepository := bolt.NewBanListRepository(tx, banListHasherMock)
	socialGraphRepository := bolt.NewSocialGraphRepository(tx, public, graphHops, banListRepository)
	receiveLogRepository := bolt.NewReceiveLogRepository(tx, messageRepository)
	pubRepository := bolt.NewPubRepository(tx)
	blobRepository := bolt.NewBlobRepository(tx)
	feedRepository := bolt.NewFeedRepository(tx, socialGraphRepository, receiveLogRepository, messageRepository, pubRepository, blobRepository, banListRepository, scuttlebutt)
	currentTimeProviderMock := mocks.NewCurrentTimeProviderMock()
	blobWantListRepository := bolt.NewBlobWantListRepository(tx, currentTimeProviderMock)
	feedWantListRepository := bolt.NewFeedWantListRepository(tx, currentTimeProviderMock)
	txTestAdapters := TxTestAdapters{
		MessageRepository:     messageRepository,
		FeedRepository:        feedRepository,
		BlobRepository:        blobRepository,
		SocialGraphRepository: socialGraphRepository,
		PubRepository:         pubRepository,
		ReceiveLog:            receiveLogRepository,
		BlobWantList:          blobWantListRepository,
		FeedWantList:          feedWantListRepository,
		BanList:               banListRepository,
		CurrentTimeProvider:   currentTimeProviderMock,
		BanListHasher:         banListHasherMock,
	}
	return txTestAdapters, nil
}

var (
	_wireHopsValue2 = hops
)

func BuildTestAdapters(db *bbolt.DB) (TestAdapters, error) {
	private, err := identity.NewPrivate()
	if err != nil {
		return TestAdapters{}, err
	}
	public := privateIdentityToPublicIdentity(private)
	logger := fixtures.SomeLogger()
	messageHMAC := formats.NewDefaultMessageHMAC()
	txRepositoriesFactory := newTxRepositoriesFactory(public, logger, messageHMAC)
	readMessageRepository := bolt.NewReadMessageRepository(db, txRepositoriesFactory)
	readFeedRepository := bolt.NewReadFeedRepository(db, txRepositoriesFactory)
	readReceiveLogRepository := bolt.NewReadReceiveLogRepository(db, txRepositoriesFactory)
	testAdapters := TestAdapters{
		MessageRepository: readMessageRepository,
		FeedRepository:    readFeedRepository,
		ReceiveLog:        readReceiveLogRepository,
	}
	return testAdapters, nil
}

func BuildTestCommands(t *testing.T) (TestCommands, error) {
	dialerMock := mocks.NewDialerMock()
	private, err := identity.NewPrivate()
	if err != nil {
		return TestCommands{}, err
	}
	roomsAliasRegisterHandler := commands.NewRoomsAliasRegisterHandler(dialerMock, private)
	roomsAliasRevokeHandler := commands.NewRoomsAliasRevokeHandler(dialerMock)
	peerManagerMock := mocks2.NewPeerManagerMock()
	processRoomAttendantEventHandler := commands.NewProcessRoomAttendantEventHandler(peerManagerMock)
	disconnectAllHandler := commands.NewDisconnectAllHandler(peerManagerMock)
	feedWantListRepositoryMock := mocks.NewFeedWantListRepositoryMock()
	feedRepositoryMock := mocks.NewFeedRepositoryMock()
	receiveLogRepositoryMock := mocks.NewReceiveLogRepositoryMock()
	adapters := commands.Adapters{
		FeedWantList: feedWantListRepositoryMock,
		Feed:         feedRepositoryMock,
		ReceiveLog:   receiveLogRepositoryMock,
	}
	mockTransactionProvider := mocks.NewMockTransactionProvider(adapters)
	currentTimeProviderMock := mocks.NewCurrentTimeProviderMock()
	downloadFeedHandler := commands.NewDownloadFeedHandler(mockTransactionProvider, currentTimeProviderMock)
	inviteRedeemerMock := mocks.NewInviteRedeemerMock()
	logger := fixtures.TestLogger(t)
	redeemInviteHandler := commands.NewRedeemInviteHandler(inviteRedeemerMock, private, logger)
	public := privateIdentityToPublicIdentity(private)
	peerInitializerMock := mocks.NewPeerInitializerMock()
	newPeerHandlerMock := mocks.NewNewPeerHandlerMock()
	acceptTunnelConnectHandler := commands.NewAcceptTunnelConnectHandler(public, peerInitializerMock, newPeerHandlerMock)
	goSSBRepoReaderMock := mocks.NewGoSSBRepoReaderMock()
	marshalerMock := mocks.NewMarshalerMock()
	migrationHandlerImportDataFromGoSSB := commands.NewMigrationHandlerImportDataFromGoSSB(goSSBRepoReaderMock, mockTransactionProvider, marshalerMock, logger)
	testCommands := TestCommands{
		RoomsAliasRegister:           roomsAliasRegisterHandler,
		RoomsAliasRevoke:             roomsAliasRevokeHandler,
		ProcessRoomAttendantEvent:    processRoomAttendantEventHandler,
		DisconnectAll:                disconnectAllHandler,
		DownloadFeed:                 downloadFeedHandler,
		RedeemInvite:                 redeemInviteHandler,
		AcceptTunnelConnect:          acceptTunnelConnectHandler,
		MigrationImportDataFromGoSSB: migrationHandlerImportDataFromGoSSB,
		PeerManager:                  peerManagerMock,
		Dialer:                       dialerMock,
		FeedWantListRepository:       feedWantListRepositoryMock,
		CurrentTimeProvider:          currentTimeProviderMock,
		InviteRedeemer:               inviteRedeemerMock,
		Local:                        public,
		PeerInitializer:              peerInitializerMock,
		NewPeerHandler:               newPeerHandlerMock,
		GoSSBRepoReader:              goSSBRepoReaderMock,
		FeedRepository:               feedRepositoryMock,
		ReceiveLog:                   receiveLogRepositoryMock,
	}
	return testCommands, nil
}

func BuildTestQueries(t *testing.T) (TestQueries, error) {
	feedRepositoryMock := mocks.NewFeedRepositoryMock()
	messagePubSub := pubsub.NewMessagePubSub()
	messagePubSubMock := mocks.NewMessagePubSubMock(messagePubSub)
	logger := fixtures.TestLogger(t)
	createHistoryStreamHandler := queries.NewCreateHistoryStreamHandler(feedRepositoryMock, messagePubSubMock, logger)
	receiveLogRepositoryMock := mocks.NewReceiveLogRepositoryMock()
	receiveLogHandler := queries.NewReceiveLogHandler(receiveLogRepositoryMock)
	private, err := identity.NewPrivate()
	if err != nil {
		return TestQueries{}, err
	}
	public := privateIdentityToPublicIdentity(private)
	publishedLogHandler, err := queries.NewPublishedLogHandler(feedRepositoryMock, receiveLogRepositoryMock, public)
	if err != nil {
		return TestQueries{}, err
	}
	messageRepositoryMock := mocks.NewMessageRepositoryMock()
	peerManagerMock := mocks2.NewPeerManagerMock()
	statusHandler := queries.NewStatusHandler(messageRepositoryMock, feedRepositoryMock, peerManagerMock)
	blobStorageMock := mocks.NewBlobStorageMock()
	getBlobHandler, err := queries.NewGetBlobHandler(blobStorageMock)
	if err != nil {
		return TestQueries{}, err
	}
	blobDownloadedPubSubMock := mocks.NewBlobDownloadedPubSubMock()
	blobDownloadedEventsHandler := queries.NewBlobDownloadedEventsHandler(blobDownloadedPubSubMock)
	dialerMock := mocks.NewDialerMock()
	roomsListAliasesHandler, err := queries.NewRoomsListAliasesHandler(dialerMock, public)
	if err != nil {
		return TestQueries{}, err
	}
	getMessageBySequenceHandler := queries.NewGetMessageBySequenceHandler(feedRepositoryMock)
	appQueries := app.Queries{
		CreateHistoryStream:  createHistoryStreamHandler,
		ReceiveLog:           receiveLogHandler,
		PublishedLog:         publishedLogHandler,
		Status:               statusHandler,
		GetBlob:              getBlobHandler,
		BlobDownloadedEvents: blobDownloadedEventsHandler,
		RoomsListAliases:     roomsListAliasesHandler,
		GetMessageBySequence: getMessageBySequenceHandler,
	}
	testQueries := TestQueries{
		Queries:              appQueries,
		FeedRepository:       feedRepositoryMock,
		MessagePubSub:        messagePubSubMock,
		MessageRepository:    messageRepositoryMock,
		PeerManager:          peerManagerMock,
		BlobStorage:          blobStorageMock,
		ReceiveLogRepository: receiveLogRepositoryMock,
		Dialer:               dialerMock,
		LocalIdentity:        public,
	}
	return testQueries, nil
}

func BuildTransactableAdapters(tx *bbolt.Tx, public identity.Public, config Config) (commands.Adapters, error) {
	graphHops := _wireHopsValue3
	banListHasher := adapters.NewBanListHasher()
	banListRepository := bolt.NewBanListRepository(tx, banListHasher)
	socialGraphRepository := bolt.NewSocialGraphRepository(tx, public, graphHops, banListRepository)
	messageContentMappings := transport.DefaultMappings()
	logger := extractLoggerFromConfig(config)
	marshaler, err := transport.NewMarshaler(messageContentMappings, logger)
	if err != nil {
		return commands.Adapters{}, err
	}
	messageHMAC := extractMessageHMACFromConfig(config)
	scuttlebutt := formats.NewScuttlebutt(marshaler, messageHMAC)
	v := newFormats(scuttlebutt)
	rawMessageIdentifier := formats.NewRawMessageIdentifier(v)
	messageRepository := bolt.NewMessageRepository(tx, rawMessageIdentifier)
	receiveLogRepository := bolt.NewReceiveLogRepository(tx, messageRepository)
	pubRepository := bolt.NewPubRepository(tx)
	blobRepository := bolt.NewBlobRepository(tx)
	feedRepository := bolt.NewFeedRepository(tx, socialGraphRepository, receiveLogRepository, messageRepository, pubRepository, blobRepository, banListRepository, scuttlebutt)
	currentTimeProvider := adapters.NewCurrentTimeProvider()
	blobWantListRepository := bolt.NewBlobWantListRepository(tx, currentTimeProvider)
	feedWantListRepository := bolt.NewFeedWantListRepository(tx, currentTimeProvider)
	commandsAdapters := commands.Adapters{
		Feed:         feedRepository,
		ReceiveLog:   receiveLogRepository,
		SocialGraph:  socialGraphRepository,
		BlobWantList: blobWantListRepository,
		FeedWantList: feedWantListRepository,
		BanList:      banListRepository,
	}
	return commandsAdapters, nil
}

var (
	_wireHopsValue3 = hops
)

func BuildTxRepositories(tx *bbolt.Tx, public identity.Public, logger logging.Logger, messageHMAC formats.MessageHMAC) (bolt.TxRepositories, error) {
	graphHops := _wireHopsValue4
	banListHasher := adapters.NewBanListHasher()
	banListRepository := bolt.NewBanListRepository(tx, banListHasher)
	socialGraphRepository := bolt.NewSocialGraphRepository(tx, public, graphHops, banListRepository)
	messageContentMappings := transport.DefaultMappings()
	marshaler, err := transport.NewMarshaler(messageContentMappings, logger)
	if err != nil {
		return bolt.TxRepositories{}, err
	}
	scuttlebutt := formats.NewScuttlebutt(marshaler, messageHMAC)
	v := newFormats(scuttlebutt)
	rawMessageIdentifier := formats.NewRawMessageIdentifier(v)
	messageRepository := bolt.NewMessageRepository(tx, rawMessageIdentifier)
	receiveLogRepository := bolt.NewReceiveLogRepository(tx, messageRepository)
	pubRepository := bolt.NewPubRepository(tx)
	blobRepository := bolt.NewBlobRepository(tx)
	feedRepository := bolt.NewFeedRepository(tx, socialGraphRepository, receiveLogRepository, messageRepository, pubRepository, blobRepository, banListRepository, scuttlebutt)
	currentTimeProvider := adapters.NewCurrentTimeProvider()
	blobWantListRepository := bolt.NewBlobWantListRepository(tx, currentTimeProvider)
	feedWantListRepository := bolt.NewFeedWantListRepository(tx, currentTimeProvider)
	wantedFeedsRepository := bolt.NewWantedFeedsRepository(socialGraphRepository, feedWantListRepository, feedRepository, banListRepository)
	txRepositories := bolt.TxRepositories{
		Feed:         feedRepository,
		Graph:        socialGraphRepository,
		ReceiveLog:   receiveLogRepository,
		Message:      messageRepository,
		Blob:         blobRepository,
		BlobWantList: blobWantListRepository,
		FeedWantList: feedWantListRepository,
		WantedFeeds:  wantedFeedsRepository,
	}
	return txRepositories, nil
}

var (
	_wireHopsValue4 = hops
)

// BuildService creates a new service which uses the provided context as a long-term context used as a base context for
// e.g. established connections.
func BuildService(contextContext context.Context, private identity.Private, config Config) (Service, func(), error) {
	networkKey := extractNetworkKeyFromConfig(config)
	currentTimeProvider := adapters.NewCurrentTimeProvider()
	handshaker, err := boxstream.NewHandshaker(private, networkKey, currentTimeProvider)
	if err != nil {
		return Service{}, nil, err
	}
	requestPubSub := pubsub.NewRequestPubSub()
	connectionIdGenerator := rpc.NewConnectionIdGenerator()
	logger := extractLoggerFromConfig(config)
	peerInitializer := transport2.NewPeerInitializer(handshaker, requestPubSub, connectionIdGenerator, logger)
	dialer, err := network.NewDialer(peerInitializer, logger)
	if err != nil {
		return Service{}, nil, err
	}
	inviteDialer := invites.NewInviteDialer(dialer, networkKey, requestPubSub, connectionIdGenerator, currentTimeProvider, logger)
	inviteRedeemer := invites2.NewInviteRedeemer(inviteDialer, logger)
	redeemInviteHandler := commands.NewRedeemInviteHandler(inviteRedeemer, private, logger)
	db, cleanup, err := newBolt(config)
	if err != nil {
		return Service{}, nil, err
	}
	public := privateIdentityToPublicIdentity(private)
	adaptersFactory := newAdaptersFactory(config, public)
	transactionProvider := bolt.NewTransactionProvider(db, adaptersFactory)
	messageContentMappings := transport.DefaultMappings()
	marshaler, err := transport.NewMarshaler(messageContentMappings, logger)
	if err != nil {
		cleanup()
		return Service{}, nil, err
	}
	followHandler := commands.NewFollowHandler(transactionProvider, private, marshaler, logger)
	transactionRawMessagePublisher := commands.NewTransactionRawMessagePublisher(transactionProvider)
	publishRawHandler := commands.NewPublishRawHandler(transactionRawMessagePublisher, private)
	publishRawAsIdentityHandler := commands.NewPublishRawAsIdentityHandler(transactionRawMessagePublisher)
	downloadFeedHandler := commands.NewDownloadFeedHandler(transactionProvider, currentTimeProvider)
	peerManagerConfig := extractPeerManagerConfigFromConfig(config)
	tunnelDialer := tunnel.NewDialer(peerInitializer)
	sessionTracker := ebt.NewSessionTracker()
	messageHMAC := extractMessageHMACFromConfig(config)
	scuttlebutt := formats.NewScuttlebutt(marshaler, messageHMAC)
	v := newFormats(scuttlebutt)
	rawMessageIdentifier := formats.NewRawMessageIdentifier(v)
	messageBuffer := commands.NewMessageBuffer(transactionProvider, logger)
	rawMessageHandler := commands.NewRawMessageHandler(rawMessageIdentifier, messageBuffer, logger)
	txRepositoriesFactory := newTxRepositoriesFactory(public, logger, messageHMAC)
	readWantedFeedsRepository := bolt.NewReadWantedFeedsRepository(db, txRepositoriesFactory)
	wantedFeedsCache := replication.NewWantedFeedsCache(readWantedFeedsRepository)
	readFeedRepository := bolt.NewReadFeedRepository(db, txRepositoriesFactory)
	messagePubSub := pubsub.NewMessagePubSub()
	createHistoryStreamHandler := queries.NewCreateHistoryStreamHandler(readFeedRepository, messagePubSub, logger)
	createHistoryStreamHandlerAdapter := ebt2.NewCreateHistoryStreamHandlerAdapter(createHistoryStreamHandler)
	sessionRunner := ebt.NewSessionRunner(logger, rawMessageHandler, wantedFeedsCache, createHistoryStreamHandlerAdapter)
	replicator := ebt.NewReplicator(sessionTracker, sessionRunner, logger)
	manager := gossip.NewManager(logger, wantedFeedsCache)
	gossipReplicator, err := gossip.NewGossipReplicator(manager, rawMessageHandler, logger)
	if err != nil {
		cleanup()
		return Service{}, nil, err
	}
	negotiator := replication.NewNegotiator(logger, replicator, gossipReplicator)
	readBlobWantListRepository := bolt.NewReadBlobWantListRepository(db, txRepositoriesFactory)
	filesystemStorage, err := newFilesystemStorage(logger, config)
	if err != nil {
		cleanup()
		return Service{}, nil, err
	}
	blobsGetDownloader := replication2.NewBlobsGetDownloader(filesystemStorage, logger)
	blobDownloadedPubSub := pubsub.NewBlobDownloadedPubSub()
	hasHandler := replication2.NewHasHandler(filesystemStorage, readBlobWantListRepository, blobsGetDownloader, blobDownloadedPubSub, logger)
	replicationManager := replication2.NewManager(readBlobWantListRepository, filesystemStorage, hasHandler, logger)
	replicationReplicator := replication2.NewReplicator(replicationManager)
	peerRPCAdapter := rooms.NewPeerRPCAdapter(logger)
	roomAttendantEventPubSub := pubsub.NewRoomAttendantEventPubSub()
	scanner := rooms.NewScanner(peerRPCAdapter, peerRPCAdapter, roomAttendantEventPubSub, logger)
	peerManager := domain.NewPeerManager(contextContext, peerManagerConfig, dialer, tunnelDialer, negotiator, replicationReplicator, scanner, logger)
	connectHandler := commands.NewConnectHandler(peerManager, logger)
	disconnectAllHandler := commands.NewDisconnectAllHandler(peerManager)
	downloadBlobHandler := commands.NewDownloadBlobHandler(transactionProvider, currentTimeProvider)
	createBlobHandler := commands.NewCreateBlobHandler(filesystemStorage)
	addToBanListHandler := commands.NewAddToBanListHandler(transactionProvider)
	removeFromBanListHandler := commands.NewRemoveFromBanListHandler(transactionProvider)
	roomsAliasRegisterHandler := commands.NewRoomsAliasRegisterHandler(dialer, private)
	roomsAliasRevokeHandler := commands.NewRoomsAliasRevokeHandler(dialer)
	boltStorage := migrations.NewBoltStorage(db)
	runner := migrations2.NewRunner(boltStorage, logger)
	goSSBRepoReader := migrations.NewGoSSBRepoReader(logger)
	migrationHandlerImportDataFromGoSSB := commands.NewMigrationHandlerImportDataFromGoSSB(goSSBRepoReader, transactionProvider, marshaler, logger)
	commandsMigrations := commands.Migrations{
		MigrationImportDataFromGoSSB: migrationHandlerImportDataFromGoSSB,
	}
	commandImportDataFromGoSSBHandlerAdapter := newCommandImportDataFromGoSSBHandlerAdapter(config, commandsMigrations)
	v2 := newMigrationsList(commandImportDataFromGoSSBHandlerAdapter)
	migrationsMigrations, err := migrations2.NewMigrations(v2)
	if err != nil {
		cleanup()
		return Service{}, nil, err
	}
	runMigrationsHandler := commands.NewRunMigrationsHandler(runner, migrationsMigrations)
	appCommands := app.Commands{
		RedeemInvite:         redeemInviteHandler,
		Follow:               followHandler,
		PublishRaw:           publishRawHandler,
		PublishRawAsIdentity: publishRawAsIdentityHandler,
		DownloadFeed:         downloadFeedHandler,
		Connect:              connectHandler,
		DisconnectAll:        disconnectAllHandler,
		DownloadBlob:         downloadBlobHandler,
		CreateBlob:           createBlobHandler,
		AddToBanList:         addToBanListHandler,
		RemoveFromBanList:    removeFromBanListHandler,
		RoomsAliasRegister:   roomsAliasRegisterHandler,
		RoomsAliasRevoke:     roomsAliasRevokeHandler,
		RunMigrations:        runMigrationsHandler,
	}
	readReceiveLogRepository := bolt.NewReadReceiveLogRepository(db, txRepositoriesFactory)
	receiveLogHandler := queries.NewReceiveLogHandler(readReceiveLogRepository)
	publishedLogHandler, err := queries.NewPublishedLogHandler(readFeedRepository, readReceiveLogRepository, public)
	if err != nil {
		cleanup()
		return Service{}, nil, err
	}
	readMessageRepository := bolt.NewReadMessageRepository(db, txRepositoriesFactory)
	statusHandler := queries.NewStatusHandler(readMessageRepository, readFeedRepository, peerManager)
	getBlobHandler, err := queries.NewGetBlobHandler(filesystemStorage)
	if err != nil {
		cleanup()
		return Service{}, nil, err
	}
	blobDownloadedEventsHandler := queries.NewBlobDownloadedEventsHandler(blobDownloadedPubSub)
	roomsListAliasesHandler, err := queries.NewRoomsListAliasesHandler(dialer, public)
	if err != nil {
		cleanup()
		return Service{}, nil, err
	}
	getMessageBySequenceHandler := queries.NewGetMessageBySequenceHandler(readFeedRepository)
	appQueries := app.Queries{
		CreateHistoryStream:  createHistoryStreamHandler,
		ReceiveLog:           receiveLogHandler,
		PublishedLog:         publishedLogHandler,
		Status:               statusHandler,
		GetBlob:              getBlobHandler,
		BlobDownloadedEvents: blobDownloadedEventsHandler,
		RoomsListAliases:     roomsListAliasesHandler,
		GetMessageBySequence: getMessageBySequenceHandler,
	}
	application := app.Application{
		Commands: appCommands,
		Queries:  appQueries,
	}
	acceptNewPeerHandler := commands.NewAcceptNewPeerHandler(peerManager)
	listener, err := newListener(contextContext, peerInitializer, acceptNewPeerHandler, config, logger)
	if err != nil {
		cleanup()
		return Service{}, nil, err
	}
	discoverer, err := local.NewDiscoverer(public, logger)
	if err != nil {
		cleanup()
		return Service{}, nil, err
	}
	processNewLocalDiscoveryHandler := commands.NewProcessNewLocalDiscoveryHandler(peerManager)
	networkDiscoverer := network2.NewDiscoverer(discoverer, processNewLocalDiscoveryHandler, logger)
	establishNewConnectionsHandler := commands.NewEstablishNewConnectionsHandler(peerManager)
	connectionEstablisher := network2.NewConnectionEstablisher(establishNewConnectionsHandler, logger)
	handlerBlobsGet := rpc2.NewHandlerBlobsGet(getBlobHandler)
	createWantsHandler := commands.NewCreateWantsHandler(replicationManager)
	handlerBlobsCreateWants := rpc2.NewHandlerBlobsCreateWants(createWantsHandler)
	handleIncomingEbtReplicateHandler := commands.NewHandleIncomingEbtReplicateHandler(replicator)
	handlerEbtReplicate := rpc2.NewHandlerEbtReplicate(handleIncomingEbtReplicateHandler)
	acceptTunnelConnectHandler := commands.NewAcceptTunnelConnectHandler(public, peerInitializer, peerManager)
	handlerTunnelConnect := rpc2.NewHandlerTunnelConnect(acceptTunnelConnectHandler)
	v3 := rpc2.NewMuxHandlers(handlerBlobsGet, handlerBlobsCreateWants, handlerEbtReplicate, handlerTunnelConnect)
	handlerCreateHistoryStream := rpc2.NewHandlerCreateHistoryStream(createHistoryStreamHandler, logger)
	v4 := rpc2.NewMuxClosingHandlers(handlerCreateHistoryStream)
	muxMux, err := mux.NewMux(logger, v3, v4)
	if err != nil {
		cleanup()
		return Service{}, nil, err
	}
	requestSubscriber := pubsub2.NewRequestSubscriber(requestPubSub, muxMux)
	processRoomAttendantEventHandler := commands.NewProcessRoomAttendantEventHandler(peerManager)
	roomAttendantEventSubscriber := pubsub2.NewRoomAttendantEventSubscriber(roomAttendantEventPubSub, processRoomAttendantEventHandler, logger)
	advertiser, err := newAdvertiser(public, config)
	if err != nil {
		cleanup()
		return Service{}, nil, err
	}
	service := NewService(application, listener, networkDiscoverer, connectionEstablisher, requestSubscriber, roomAttendantEventSubscriber, advertiser, messageBuffer, createHistoryStreamHandler)
	return service, func() {
		cleanup()
	}, nil
}

// wire.go:

type BadgerNoTxTestAdapters struct {
	NoTxTestAdapters    notx.TestAdapters
	TransactionProvider *badger.TestTransactionProvider
	Dependencies        *badger.TestAdaptersDependencies
}

type BadgerTestAdapters struct {
	TransactionProvider *badger.TestTransactionProvider
	Dependencies        *badger.TestAdaptersDependencies
}

type TxTestAdapters struct {
	MessageRepository     *bolt.MessageRepository
	FeedRepository        *bolt.FeedRepository
	BlobRepository        *bolt.BlobRepository
	SocialGraphRepository *bolt.SocialGraphRepository
	PubRepository         *bolt.PubRepository
	ReceiveLog            *bolt.ReceiveLogRepository
	BlobWantList          *bolt.BlobWantListRepository
	FeedWantList          *bolt.FeedWantListRepository
	BanList               *bolt.BanListRepository

	CurrentTimeProvider *mocks.CurrentTimeProviderMock
	BanListHasher       *mocks.BanListHasherMock
}

type TestAdapters struct {
	MessageRepository *bolt.ReadMessageRepository
	FeedRepository    *bolt.ReadFeedRepository
	ReceiveLog        *bolt.ReadReceiveLogRepository
}

type TestCommands struct {
	RoomsAliasRegister        *commands.RoomsAliasRegisterHandler
	RoomsAliasRevoke          *commands.RoomsAliasRevokeHandler
	ProcessRoomAttendantEvent *commands.ProcessRoomAttendantEventHandler
	DisconnectAll             *commands.DisconnectAllHandler
	DownloadFeed              *commands.DownloadFeedHandler
	RedeemInvite              *commands.RedeemInviteHandler
	AcceptTunnelConnect       *commands.AcceptTunnelConnectHandler

	MigrationImportDataFromGoSSB *commands.MigrationHandlerImportDataFromGoSSB

	PeerManager            *mocks2.PeerManagerMock
	Dialer                 *mocks.DialerMock
	FeedWantListRepository *mocks.FeedWantListRepositoryMock
	CurrentTimeProvider    *mocks.CurrentTimeProviderMock
	InviteRedeemer         *mocks.InviteRedeemerMock
	Local                  identity.Public
	PeerInitializer        *mocks.PeerInitializerMock
	NewPeerHandler         *mocks.NewPeerHandlerMock
	GoSSBRepoReader        *mocks.GoSSBRepoReaderMock
	FeedRepository         *mocks.FeedRepositoryMock
	ReceiveLog             *mocks.ReceiveLogRepositoryMock
}

type TestQueries struct {
	Queries app.Queries

	FeedRepository       *mocks.FeedRepositoryMock
	MessagePubSub        *mocks.MessagePubSubMock
	MessageRepository    *mocks.MessageRepositoryMock
	PeerManager          *mocks2.PeerManagerMock
	BlobStorage          *mocks.BlobStorageMock
	ReceiveLogRepository *mocks.ReceiveLogRepositoryMock
	Dialer               *mocks.DialerMock

	LocalIdentity identity.Public
}

var replicatorSet = wire.NewSet(gossip.NewManager, wire.Bind(new(gossip.ReplicationManager), new(*gossip.Manager)), gossip.NewGossipReplicator, wire.Bind(new(replication.CreateHistoryStreamReplicator), new(*gossip.GossipReplicator)), ebt.NewReplicator, wire.Bind(new(replication.EpidemicBroadcastTreesReplicator), new(ebt.Replicator)), replication.NewWantedFeedsCache, wire.Bind(new(gossip.ContactsStorage), new(*replication.WantedFeedsCache)), wire.Bind(new(ebt.ContactsStorage), new(*replication.WantedFeedsCache)), ebt.NewSessionTracker, wire.Bind(new(ebt.Tracker), new(*ebt.SessionTracker)), ebt.NewSessionRunner, wire.Bind(new(ebt.Runner), new(*ebt.SessionRunner)), replication.NewNegotiator, wire.Bind(new(domain.MessageReplicator), new(*replication.Negotiator)))

var blobReplicatorSet = wire.NewSet(replication2.NewManager, wire.Bind(new(replication2.ReplicationManager), new(*replication2.Manager)), wire.Bind(new(commands.BlobReplicationManager), new(*replication2.Manager)), replication2.NewReplicator, wire.Bind(new(domain.BlobReplicator), new(*replication2.Replicator)), replication2.NewBlobsGetDownloader, wire.Bind(new(replication2.Downloader), new(*replication2.BlobsGetDownloader)), replication2.NewHasHandler, wire.Bind(new(replication2.HasBlobHandler), new(*replication2.HasHandler)))

var hops = graph.MustNewHops(3)

func newAdvertiser(l identity.Public, config Config) (*local.Advertiser, error) {
	return local.NewAdvertiser(l, config.ListenAddress)
}

func newAdaptersFactory(config Config, local2 identity.Public) bolt.AdaptersFactory {
	return func(tx *bbolt.Tx) (commands.Adapters, error) {
		return BuildTransactableAdapters(tx, local2, config)
	}
}

func newBolt(config Config) (*bbolt.DB, func(), error) {
	filename := path.Join(config.DataDirectory, "database.bolt")
	b, err := bbolt.Open(filename, 0600, &bbolt.Options{Timeout: 5 * time.Second})
	if err != nil {
		return nil, nil, errors.Wrap(err, "could not open the database, is something else reading it?")
	}
	return b, func() {
		if err := b.Close(); err != nil {
			config.Logger.WithError(err).Error("error closing the database")
		}
	}, nil
}

func newBadger(config Config) (*badger2.DB, func(), error) {
	badgerDirectory := filepath.Join(config.DataDirectory, "badger")

	options := badger2.DefaultOptions(badgerDirectory)

	db, err := badger2.Open(options)
	if err != nil {
		return nil, nil, errors.Wrap(err, "failed to open the database")
	}

	return db, func() {
		if err := db.Close(); err != nil {
			config.Logger.WithError(err).Error("error closing the database")
		}
	}, nil

}

func privateIdentityToPublicIdentity(p identity.Private) identity.Public {
	return p.Public()
}
