// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package tests

import (
	"testing"

	"github.com/planetary-social/scuttlego/fixtures"
	"github.com/planetary-social/scuttlego/service/adapters/migrations"
	"github.com/planetary-social/scuttlego/service/app/commands"
)

// Injectors from wire.go:

func BuildCommandIntegrationTest(t *testing.T) CommandIntegrationTest {
	logger := fixtures.TestLogger(t)
	goSSBRepoReader := migrations.NewGoSSBRepoReader(logger)
	migrationHandlerDeleteGoSSBRepositoryInOldFormat := commands.NewMigrationHandlerDeleteGoSSBRepositoryInOldFormat(goSSBRepoReader, logger)
	commandIntegrationTest := CommandIntegrationTest{
		DeleteGoSSBRepositoryInOldFormat: migrationHandlerDeleteGoSSBRepositoryInOldFormat,
	}
	return commandIntegrationTest
}

// wire.go:

type CommandIntegrationTest struct {
	DeleteGoSSBRepositoryInOldFormat *commands.MigrationHandlerDeleteGoSSBRepositoryInOldFormat
}
